name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: python:3.8.3-slim-buster

    steps:
    - uses: actions/checkout@v2

    - name: Run evaluate.py with arguments `--help`
      run: python evaluate.py --help
